inherits = "tokyonight"
"ui.background" ={}
"ui.statusline.inactive" = { fg = "stone", bg = "panel" }
"ui.statusline.normal" = { bg = "aqua", fg = "panel" }
"ui.statusline.insert" = { bg = "leaf", fg = "panel" }
"ui.statusline.select" = { bg = "sky", fg = "panel" }
